AWSTemplateFormatVersion: 2010-09-09
Description: Udacity Challenge3 stack
Parameters: 
  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String
  AMItoUse:
    Description: Amazon Linux image to use for the EC2 instance
    Type: String
  EC2InstanceType:
    Description: Instance type of the EC2 instance
    Type: String

Resources: 
  RoleForSSMAccess:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
       - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  ServerInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - !Ref "RoleForSSMAccess"
  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound traffic to webserver on port 80
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-WebServer-SG
  ServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: formation_server_key
      ImageId: !Ref AMItoUse
      InstanceType: !Ref EC2InstanceType
      IamInstanceProfile: !Ref ServerInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet: 
            - !Ref WebAccessSecurityGroup
          SubnetId: 
            Fn::ImportValue: !Sub ${EnvironmentName}-PrivSubnet1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          echo "Udacity Demo Web Server Up and Running!" > index.html
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Webserver