AWSTemplateFormatVersion: 2010-09-09
Description: RDS Template for Udacity Project
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String
  DBInstanceClass:
    Description: The compute and memory capacity of the DB instance.
    Type: String
  DBPort:
    Description: The database port 
    Type: String
    Default: "3306"
  DBStorageType:
    Description: Specifies the storage type to be associated with the DB instance.
    Type: String
    Default: gp2
  DBAllocatedStorage:
    Description: The amount of storage in gibibytes (GiB) to be initially allocated for the database instance.
    Type: String
  DBSecurityGroup:
    Description: DB security group
    Type: AWS::EC2::SecurityGroup::Id
  DBMasterUsername:
    Description: DB master username
    Type: AWS::SSM::Parameter::Value<String>
  DBMasterPassword: 
    Description: Password for RDS instance master user
    Type: AWS::SSM::Parameter::Value<String>
  DBName:
    Description: Name of a database to be created
    Type: AWS::SSM::Parameter::Value<String>
Resources: 
  myDBSubnetGroup1:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnet group for the RDS instance
      SubnetIds:
        - Fn::ImportValue: !Sub ${EnvironmentName}-Private1-SN
        - Fn::ImportValue: !Sub ${EnvironmentName}-Private2-SN
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref myDBSubnetGroup1
      Engine: MySQL
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      MultiAZ: true
      Port: !Ref DBPort
      PubliclyAccessible: false
      StorageType: !Ref DBStorageType
      DeletionProtection: true
      VPCSecurityGroups:
       - !Ref DBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-RDS